### ISSUE TITLE
Input Data-Format

### ISSUE THREAD

**Issue by Chipato1** [m-qiang/CortexODE#2]
Hey, I am currently trying to test out your model and train it on my data.
If I try to load the data provided in the test folder I see that the surfaces do not seem to match the MRI even if I interpret it in RAS or LPS encoding.
My data is MNI-152 registered FreeSurfer output.

Could you clarify which format the data should have? And maybe which transformations one should do before using it?
Thank you for your work! 

All the best,
Carl

**Comment by MavPig** [comment]
@Chipato1 Hey, is there any update about the "mismatch"?

**Comment by MavPig** [comment]
ps: the mismatching result with given example data(yellow is the gt, blue is the pred)
![image](https://github.com/m-qiang/CortexODE/assets/45254223/f5d36c3d-c715-401d-8aee-74ee72eae1d3)
